/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.TextField;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import tarea_2.DetalleVenta;
import tarea_2.VendedorDao;
import tarea_2.Vendedor;
import tarea_2.Venta;
import tarea_2.VentaDao;

/**
 *
 * @author ferna
 */
public class VentasForm extends javax.swing.JFrame {
    VendedorDao dao = new VendedorDao();
    Vendedor v = new Vendedor();
    
    VentaDao daoVen = new VentaDao();
    Venta ven = new Venta();
    
    DetalleVenta dven = new DetalleVenta();
    int cantMine;
    int cantFort;
    int cantCod;
    /**
     * Creates new form VentasForm
     */
    public VentasForm() {
        initComponents();
        setLocationRelativeTo(null);
        Calendar c = new GregorianCalendar();
        txtFecha.setText(""+c.get(Calendar.YEAR)+"-"+c.get(Calendar.MONTH)+"-"+c.get(Calendar.DAY_OF_MONTH));
        SetImageLabel(label2, "src/Imagen/COD.png");
        SetImageLabel(label1, "src/Imagen/Minecraft.jpg");
        SetImageLabel(label3, "src/Imagen/Fornite.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbMine = new javax.swing.JCheckBox();
        cbCod = new javax.swing.JCheckBox();
        cbFort = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadMine = new javax.swing.JTextField();
        txtCantidadCod = new javax.swing.JTextField();
        txtCantidadFort = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Venta"));

        jLabel1.setText("Vendedor: ");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        cbMine.setText("Minecraft");
        cbMine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMineActionPerformed(evt);
            }
        });

        cbCod.setText("Call of Duty");

        cbFort.setText("Fortnite");

        jLabel2.setText("Precio:");

        jLabel3.setText("8800");

        jLabel4.setText("34500");

        jLabel5.setText("58200");

        label2.setBackground(new java.awt.Color(255, 153, 153));
        label2.setForeground(new java.awt.Color(255, 153, 153));
        label2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label3.setBackground(new java.awt.Color(255, 153, 153));
        label3.setForeground(new java.awt.Color(255, 153, 153));
        label3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label1.setBackground(new java.awt.Color(0, 204, 204));
        label1.setForeground(new java.awt.Color(255, 153, 204));
        label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setText("Cantidad:");

        txtCantidadMine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadMineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadMine, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(txtCantidadCod, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMine, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCod, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFort, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCantidadFort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMine)
                    .addComponent(cbCod)
                    .addComponent(cbFort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCantidadMine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadFort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        btnRegistro.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistro.setForeground(new java.awt.Color(0, 102, 102));
        btnRegistro.setText("Finalizar Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnVendedor.setBackground(new java.awt.Color(204, 204, 255));
        btnVendedor.setText("Vendedor estrella");
        btnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorActionPerformed(evt);
            }
        });

        jLabel7.setText("Rut:");

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha:");

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnVendedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro)
                    .addComponent(btnVendedor))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMineActionPerformed

    private void txtCantidadMineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadMineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMineActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        
        //Método que registre al vendedor dado los productos
        //insertarVendedor();
        insertargame();
        //guardarVenta();
        //guardarDetalleVenta();
        limpiarCampos();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedorActionPerformed
        //calcularEstrella();

    }//GEN-LAST:event_btnVendedorActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        buscarVendedor();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasForm().setVisible(true);
            }
        });
    };
    void guardarVenta(){
        int idv=v.getId();
        
        String fecha = txtFecha.getText();
        ven.setVendedorId(idv);
        ven.setFecha(fecha);
        //TODO: AGREGAR FUNCIÓN CALCULAR MONTO VENTA dao
        //ven.setMontoVenta();
        daoVen.guardarVenta(ven);
        
        
    }
    void guardarDetalleVenta() {
        String idv = daoVen.idVent();
        int idve = Integer.parseInt(idv);
//TODO:VERIFICAR TIPO DE PRODUCTO Y ASIGNAR DETALLE VENTA
        for(int i=0; i<3; i++) {
            dven.setIdVenta(idve);
            dven.setIdProducto(1);
            dven.setCantidad(cantCod);
            daoVen.GuardarDetalleVenta(dven);
        }
        
    }
    
    void buscarVendedor() {
        String rut = txtRut.getText();
        int r;
        if(txtRut.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar rut");
        } else {
           v= dao.listarId(rut);
           if(v.getRut() != "") {
               txtNombre.setText(v.getNom());
           } else {
               JOptionPane.showMessageDialog(null, "Vendedor no registrado, debe registrarlo");
               
           }

           
             //Registro de vendedor único

        }
    }
    
    void insertarVendedor() {
        String nom = txtNombre.getText();
        String rut = txtRut.getText();
        v = dao.listarId(rut);
        if(v.getRut().equals(rut)) {
            System.out.println("Ya existe vendedor con ese rut");
        }
        Object[] ob = new Object[2];
        ob[0]=nom;
        ob[1]=rut;
        dao.add(ob);
        JOptionPane.showMessageDialog(null, "Vendedor guardado con éxito");

               
    }
    void insertargame(){
        
        double comMine;
        double comFort;
        double comCod;
        double comTotal;
        
        
        String nom = txtNombre.getText();
        String rut = txtRut.getText();
        Object[] ob = new Object[6];
        
        if(cbMine.isSelected() && cbFort.isSelected()  && cbCod.isSelected()) {
            cantMine = Integer.parseInt(txtCantidadMine.getText());
            cantFort = Integer.parseInt(txtCantidadFort.getText());
            cantCod = Integer.parseInt(txtCantidadCod.getText());
            
            comMine = cantMine*8800*0.04;
            comFort = cantFort*58200*0.09;
            comCod = cantCod *34500*0.06;
            
            comTotal = comMine+comFort+comCod;
      
            ob[0]=nom;
            ob[1]=rut;
            ob[2] = comCod;
            ob[3]= comFort;
            ob[4]= comMine;
            ob[5]= comTotal;
            
            dao.add(ob);
            JOptionPane.showMessageDialog(null, "Vendedor guardado");
            
        } else if(cbMine.isSelected() && cbFort.isSelected()){
            cantMine = Integer.parseInt(txtCantidadMine.getText());
            cantFort = Integer.parseInt(txtCantidadFort.getText());
            cantCod = 0;
            
            comMine = cantMine*8800*0.04;
            comFort = cantFort*58200*0.09;
            comCod = cantCod *34500*0.06;
            
            comTotal = comMine+comFort+comCod;
      
            ob[0]=nom;
            ob[1]=rut;
            ob[2] = comCod;
            ob[3]= comFort;
            ob[4]= comMine;
            ob[5]= comTotal;
            dao.add(ob);
            JOptionPane.showMessageDialog(null, "Vendedor guardado");



        } else if(cbFort.isSelected()  && cbCod.isSelected()) {
            cantMine = 0;
            cantFort = Integer.parseInt(txtCantidadFort.getText());
            cantCod = Integer.parseInt(txtCantidadCod.getText());
            
            comMine = cantMine*8800*0.04;
            comFort = cantFort*58200*0.09;
            comCod = cantCod *34500*0.06;
            
            comTotal = comMine+comFort+comCod;
      
            ob[0]=nom;
            ob[1]=rut;
            ob[2] = comCod;
            ob[3]= comFort;
            ob[4]= comMine;
            ob[5]= comTotal;
            dao.add(ob);
            JOptionPane.showMessageDialog(null, "Vendedor guardado");

            
        } else if(cbMine.isSelected() && cbCod.isSelected()) {
            cantMine = Integer.parseInt(txtCantidadMine.getText());
            cantFort =0;
            cantCod = Integer.parseInt(txtCantidadCod.getText());
            
            comMine = cantMine*8800*0.04;
            comFort = cantFort*58200*0.09;
            comCod = cantCod *34500*0.06;
            
            comTotal = comMine+comFort+comCod;
      
            ob[0]=nom;
            ob[1]=rut;
            ob[2] = comCod;
            ob[3]= comFort;
            ob[4]= comMine;
            ob[5]= comTotal;
            dao.add(ob);
            JOptionPane.showMessageDialog(null, "Vendedor guardado");
        } else if(cbMine.isSelected()) {
            cantMine = Integer.parseInt(txtCantidadMine.getText());
            cantFort =0;
            cantCod = 0;
            comMine = cantMine*8800*0.04;
            comFort = cantFort*58200*0.09;
            comCod = cantCod *34500*0.06;
            
            comTotal = comMine+comFort+comCod;
      
            ob[0]=nom;
            ob[1]=rut;
            ob[2] = comCod;
            ob[3]= comFort;
            ob[4]= comMine;
            ob[5]= comTotal;
            dao.add(ob);
            JOptionPane.showMessageDialog(null, "Vendedor guardado");
        } else if(cbFort.isSelected()) {
            cantMine = 0;
            cantFort = Integer.parseInt(txtCantidadFort.getText());
            cantCod = 0;

            comMine = cantMine*8800*0.04;
            comFort = cantFort*58200*0.09;
            comCod = cantCod *34500*0.06;
            
            comTotal = comMine+comFort+comCod;
      
            ob[0]=nom;
            ob[1]=rut;
            ob[2] = comCod;
            ob[3]= comFort;
            ob[4]= comMine;
            ob[5]= comTotal;
            dao.add(ob);
            JOptionPane.showMessageDialog(null, "Vendedor guardado");

        } else if(cbCod.isSelected()) {
            cantMine = 0;
            cantFort = 0;
            cantCod = Integer.parseInt(txtCantidadCod.getText());
            
            comMine = cantMine*8800*0.04;
            comFort = cantFort*58200*0.09;
            comCod = cantCod *34500*0.06;
            
            comTotal = comMine+comFort+comCod;
      
            ob[0]=nom;
            ob[1]=rut;
            ob[2] = comCod;
            ob[3]= comFort;
            ob[4]= comMine;
            ob[5]= comTotal;
            dao.add(ob);
            JOptionPane.showMessageDialog(null, "Vendedor guardado");
        } else {
            cantMine = 0;
            cantFort = 0;
            cantCod = 0;

            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguno, vuelva a intentarlo");

        }

        
    }
    private void limpiarCampos(){
        txtCantidadMine.setText("");
        txtCantidadCod.setText("");
        txtCantidadFort.setText("");
        txtNombre.setText("");
        txtRut.setText("");
    }
    
    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    // V

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JCheckBox cbCod;
    private javax.swing.JCheckBox cbFort;
    private javax.swing.JCheckBox cbMine;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JTextField txtCantidadCod;
    private javax.swing.JTextField txtCantidadFort;
    private javax.swing.JTextField txtCantidadMine;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
